#!/Users/dsanford/anaconda/bin/python

import re
import sys
from os.path import isfile

from lib.wiki_module import query_category
from lib.wiki_module import query_page
from lib.database_module import create_or_update_category_in_database
from lib.database_module import create_or_update_page_in_database

if len(sys.argv) < 2:
    print "No arguments passed.  Need at least one category name or file with category list."
    quit()



def categories_from_file(filename):
    """
    Get categories from a passed yml file
    """
    if isfile(filename) is not True:
        return []

    fin = open(filename)
    terms = []
    for line in fin:
        match = re.match(r"[\W]+(\w.+)",line)
        if match != None:
            terms.append(match.group(1))

    return terms



def category_list(term_list):
    """
    Parse the list of inputs (possibly a combination of category names and yml files) into a list of categories to search for
    """

    categories = []

    for arg in term_list:
        if '.' in arg:
            categories = categories + categories_from_file(arg)

        else:
            match = re.match(r"(\w.+)",arg)
            if match != None:
                categories.append(match.group(1))  

    return categories



search_terms = category_list(sys.argv[1:])



for term in search_terms:

    category = query_category(term)

    if category['categoryid'] is '-1':
        print "ERROR : Category name \""+term+"\" does not exist" 
        continue

    create_or_update_category_in_database(category['categoryid'], term)

    print category['categoryid'], term

    for page_info in category['pages']:
        page = query_page(str(page_info['pageid']))

        print "\t",page['pageid'], page_info['title']

        create_or_update_page_in_database(page_info['pageid'],
                                          category['categoryid'],
                                          page_info['title'],
                                          page['text'])
